### ISSUE TITLE
Feature request: Fix black screen bug on Proton/Steam Deck

### ISSUE THREAD

**Issue by zxtheproto** [M3tox/TAOOT#1]
This may be beyond the scope of the project, but I wondered if it would be possible to fix the black screen bug when running the game under Proton. 

Currently, when you start up the game, the title screen isn’t initially visible, requiring you to click blindly on the Tour or Game buttons by scrolling over them. (This also affects the Help screen to a certain degree, as well as some other areas.)

**Comment by M3tox** [comment]
Interesting, its the first time that I heared of this issue. However, most errores I fixed were caused by scripts, but this issue seems to be a problem in the communication between the game and the graphic API. I am afraid as long as no modernized engine is provided, I can't track down this issue.
The source code would help a lot in these kind of problems, but my request to view it was ignored.

**Comment by JoshuaPettus** [comment]
Honestly especially on linux it's best to run the game in windows 3.1 within dosbox staging.  That will avoid these graphics api issues.
