### ISSUE TITLE
pixels flash different colors when turning right in the full version of the patch

### ISSUE THREAD

**Issue by ghasttastic1912** [M3tox/TAOOT#2]
this bug occurs after the patch that fixes the graphics resolution is installed. it only happens when turning right.

**Comment by M3tox** [comment]
The patch technically does not change anything about the resolution. What it does it redirecting the images that are stored in the files, by skipping the buffer image. Processor speed, RAM speed and the fact that this version is directly read from hard drive, makes this buffer image completely obsolete, so the patch makes it so that the "better frame" will be loaded directly. However, if this causes weird graphical glitches on your system, then it appears that this technique is not compatible with your computer.
Since that would be a hardware related issue, there is nothing I can do about it.
All you can do now is reinstall it again and pray that it works, but if it won't you must stick with the default version, sorry.

**Comment by ghasttastic1912** [comment]
i think i shouldve phrased this better, it happens during the turning animation. not at the final image
